# Generated by Django 2.2.12 on 2020-05-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0003_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='persona',
        ),
    ]
