# Generated by Django 2.2.12 on 2020-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimagenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('cedula', models.CharField(max_length=10)),
                ('resenia', models.CharField(max_length=1400)),
                ('formal', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=140)),
                ('provincia', models.CharField(choices=[('sanjose', 'San Jose'), ('alajuela', 'Alajuela'), ('heredia', 'Heredia'), ('cartago', 'Cartago'), ('limon', 'Limón'), ('puntarenas', 'Puntarenas'), ('guanacaste', 'Guanacaste')], max_length=10)),
                ('canton', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='imagenesmodel',
            name='cedula',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenesmodel',
            name='foto_de_perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagenesmodel',
            name='foto_de_producto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagenesmodel',
            name='nombre',
            field=models.CharField(default=0, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenesmodel',
            name='imagenes_field',
            field=models.ImageField(upload_to='media/<django.db.models.fields.CharField>'),
        ),
    ]
