# Generated by Django 2.2.12 on 2020-05-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appimagenes', '0002_auto_20200524_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenesModel',
        ),
    ]
