# Generated by Django 2.2.12 on 2020-05-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimagenes', '0003_delete_imagenesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('cedula', models.CharField(max_length=10)),
                ('foto_de_perfil', models.BooleanField(default=False)),
                ('foto_de_producto', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='imagenes/%Y/%m/%d')),
            ],
        ),
    ]
