# Generated by Django 2.2.12 on 2020-05-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appimagenes', '0004_imagenesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenesModel',
        ),
    ]
