# Generated by Django 2.2.12 on 2020-06-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appimagenes', '0006_imagenesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenesModel',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
